import "@/styles/globals.css";
import { Noto_Sans_JP } from "next/font/google";
import { type Metadata } from "next";
import { cookies } from "next/headers";
import { Toaster } from "@/components/ui/toaster";
import SidebarLayout from "./layouts/SidebarLayout";
import AppProviders from "@/components/providers/AppProviders";
import AppSidebar from "@/app/_components/Sidebar/AppSidebar";

const notoSansJP = Noto_Sans_JP({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar:state")?.value === "true";

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={notoSansJP.className}>
        <AppProviders>
          <SidebarLayout defaultOpen={defaultOpen} sidebar={<AppSidebar />}>
            {children}
            <Toaster />
          </SidebarLayout>
        </AppProviders>
      </body>
    </html>
  );
}
