import "@/styles/globals.css";

import { Noto_Sans_JP } from "next/font/google";
// import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import SessionProviderWrapper from "@/components/SessionProviderWrapper";

const notoSansJP = Noto_Sans_JP({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={notoSansJP.className}>
        <SessionProviderWrapper>{children}</SessionProviderWrapper>
      </body>
    </html>
  );
}
